import { formatTypeDecl } from "../src/prompts/codegen";
import { TypeDecl, Span, TypeRef, Field } from "../src/types";
import { spawnSync } from "child_process";
import * as path from "path";
import * as fs from "fs";

describe("Type Consistency Verification", () => {
  const dummySpan: Span = { start: 0, end: 0 };
  
  const createTypeRef = (name: string): TypeRef => ({
    name,
    type_args: [],
    union_members: [],
    intersection_members: [],
    span: dummySpan,
  });

  test("should format Alias types correctly", () => {
    const aliasDecl: TypeDecl = {
      name: "UserId",
      type_params: [],
      kind: { Alias: createTypeRef("UUID") },
      visibility: "Public",
      doc_comment: "The unique identifier of a user",
      span: dummySpan,
    };

    const formatted = formatTypeDecl(aliasDecl);
    expect(formatted).toBe("export type UserId = string;");
  });

  test("should format Struct types correctly", () => {
    const fields: Field[] = [
      {
        name: "id",
        ty: createTypeRef("UserId"),
        default: null,
        doc_comment: "Unique ID",
        span: dummySpan,
      },
      {
        name: "email",
        ty: createTypeRef("String"), // formatTypeRef maps String to string
        default: null,
        doc_comment: null,
        span: dummySpan,
      }
    ];

    const structDecl: TypeDecl = {
      name: "User",
      type_params: [],
      kind: { Struct: { fields, span: dummySpan } },
      visibility: "Public",
      doc_comment: null,
      span: dummySpan,
    };

    const formatted = formatTypeDecl(structDecl);
    expect(formatted).toContain("export interface User {");
    expect(formatted).toContain("id: UserId;");
    expect(formatted).toContain("email: string;");
  });

  test("should format Enum types correctly", () => {
    const enumDecl: TypeDecl = {
      name: "UserRole",
      type_params: [],
      kind: {
        Enum: {
          variants: [
            { name: "Admin", fields: [], span: dummySpan },
            { name: "User", fields: [], span: dummySpan }
          ],
          span: dummySpan
        }
      },
      visibility: "Public",
      doc_comment: null,
      span: dummySpan,
    };

    const formatted = formatTypeDecl(enumDecl);
    expect(formatted).toContain("export enum UserRole {");
    expect(formatted).toContain("Admin = 'Admin',");
    expect(formatted).toContain("User = 'User',");
  });

  test("should format Refined types correctly", () => {
    const refinedDecl: TypeDecl = {
      name: "DepositAmount",
      type_params: [],
      kind: {
        Refined: {
          base: createTypeRef("Money"),
          constraints: [],
          span: dummySpan
        }
      },
      visibility: "Public",
      doc_comment: null,
      span: dummySpan,
    };

    const formatted = formatTypeDecl(refinedDecl);
    expect(formatted).toBe("export type DepositAmount = number; // Refined type with constraints");
  });

  test("should be consistent with type mappings generated by Rust compiler via Specta", () => {
    const rootDir = path.resolve(__dirname, "../..");
    const dummySpec = `module test.consistency
type DummyId = UUID
type User = struct { id: DummyId }
`;
    const cacheDir = path.join(rootDir, ".omni-cache");
    if (!fs.existsSync(cacheDir)) {
      fs.mkdirSync(cacheDir, { recursive: true });
    }
    const specPath = path.join(cacheDir, "consistency_test_spec.omni");
    fs.writeFileSync(specPath, dummySpec, "utf8");

    // Execute target/debug/omni to serialize the IR
    const runResult = spawnSync(
      "cargo",
      ["run", "--bin", "omni", "--", "build", ".omni-cache/consistency_test_spec.omni", "--target", "typescript"],
      {
        cwd: rootDir,
        env: {
          ...process.env,
          OMNI_MOCK_LLM: "true"
        }
      }
    );

    if (runResult.status !== 0) {
      console.warn("Skipping Rust compiler consistency check because omni binary is not built or failed");
      return;
    }

    const irPath = path.join(rootDir, ".omni-cache", "consistency_test_spec_ir.json");
    expect(fs.existsSync(irPath)).toBe(true);

    const ir = JSON.parse(fs.readFileSync(irPath, "utf8"));
    const typeMappings = ir.type_mappings;
    expect(typeMappings).toBeDefined();
    expect(Array.isArray(typeMappings)).toBe(true);

    for (const mapping of typeMappings) {
      const { omni_type, target_type } = mapping;
      const typeRef: TypeRef = {
        name: omni_type,
        type_args: [],
        union_members: [],
        intersection_members: [],
        span: { start: 0, end: 0 }
      };

      const typeDecl: TypeDecl = {
        name: "TestType",
        type_params: [],
        kind: { Alias: typeRef },
        visibility: "Public",
        doc_comment: null,
        span: { start: 0, end: 0 }
      };

      const formatted = formatTypeDecl(typeDecl, typeMappings);
      expect(formatted).toBe(`export type TestType = ${target_type};`);
    }

    fs.rmSync(specPath, { force: true });
    fs.rmSync(irPath, { force: true });
  });
});
