import * as fs from "fs";
import * as path from "path";
import pc from "picocolors";
import { SchemaGeneratorPlugin, resolveTypeRef } from "./base";
import { SpecIR, TypeRef, Expression } from "../types";
import { injectRelationFields, PrismaSchemaDecl, formatExpression } from "./prisma";

export function mapTypeToSql(typeRef: TypeRef, ir?: SpecIR): string {
  const resolved = resolveTypeRef(typeRef, ir);
  const name = resolved.name;
  if (name === "Option" && resolved.type_args.length > 0) {
    return mapTypeToSql(resolved.type_args[0], ir);
  }
  if (name === "List" && resolved.type_args.length > 0) {
    return mapTypeToSql(resolved.type_args[0], ir) + "[]";
  }

  switch (name) {
    case "UUID": return "VARCHAR(36)";
    case "String": return "VARCHAR(255)";
    case "Int": return "INTEGER";
    case "Float": return "DOUBLE PRECISION";
    case "Boolean": return "BOOLEAN";
    case "DateTime": return "TIMESTAMP";
    case "Decimal": return "NUMERIC";
    default: return "VARCHAR(255)";
  }
}

export function generateSqlDdl(ir: SpecIR): string | null {
  let schemaDecl: any = null;
  if (ir.source_file && ir.source_file.declarations) {
    for (const decl of ir.source_file.declarations) {
      if ("Schema" in decl) {
        schemaDecl = decl.Schema;
        break;
      }
    }
  }

  if (!schemaDecl) {
    return null;
  }

  const schema: PrismaSchemaDecl = JSON.parse(JSON.stringify(schemaDecl));
  injectRelationFields(schema);

  const lines: string[] = [];
  lines.push(`-- Generated by OmniLang Compiler. Do not edit manually.`);
  lines.push(``);

  const indexStatements: string[] = [];
  const foreignKeyStatements: string[] = [];

  for (const entity of schema.entities) {
    lines.push(`CREATE TABLE ${entity.name} (`);
    const columns: string[] = [];

    for (const field of entity.fields) {
      // Skip virtual relation fields
      const isModelRelation = schema.entities.some((e) => e.name === field.ty.name);
      if (isModelRelation && !field.relationConfig) {
        continue;
      }

      if (field.relationConfig) {
        const fkFields = field.relationConfig.fields;
        const refFields = field.relationConfig.references;
        const parentTable = field.ty.name;

        for (let i = 0; i < fkFields.length; i++) {
          foreignKeyStatements.push(
            `ALTER TABLE ${entity.name} ADD CONSTRAINT fk_${entity.name.toLowerCase()}_${parentTable.toLowerCase()} FOREIGN KEY (${fkFields[i]}) REFERENCES ${parentTable}(${refFields[i]});`
          );
        }
        continue;
      }

      const sqlTy = mapTypeToSql(field.ty, ir);
      let colDef = `  ${field.name.padEnd(15)} ${sqlTy}`;

      let isPrimary = false;
      let isNullable = field.ty.name === "Option";

      if (field.decorators) {
        for (const dec of field.decorators) {
          if (dec.name === "primary") {
            isPrimary = true;
          } else if (dec.name === "unique") {
            colDef += " UNIQUE";
          } else if (dec.name === "indexed") {
            indexStatements.push(`CREATE INDEX idx_${entity.name.toLowerCase()}_${field.name} ON ${entity.name}(${field.name});`);
          } else if (dec.name === "default") {
            const argStr = dec.args.map(formatExpression).join(", ");
            colDef += ` DEFAULT ${argStr}`;
          }
        }
      }

      if (isPrimary) {
        colDef += " PRIMARY KEY";
      } else if (!isNullable) {
        colDef += " NOT NULL";
      }

      if (field.default && !colDef.includes("DEFAULT")) {
        colDef += ` DEFAULT ${formatExpression(field.default)}`;
      }

      columns.push(colDef);
    }

    lines.push(columns.join(",\n"));
    lines.push(`);`);
    lines.push(``);
  }

  // Generate explicit indexes
  if (schema.indexes) {
    for (const idx of schema.indexes) {
      const fieldList = idx.fields.join(", ");
      const indexName = `idx_${idx.entity.toLowerCase()}_${idx.fields.join("_")}`;
      indexStatements.push(`CREATE INDEX ${indexName} ON ${idx.entity}(${fieldList});`);
    }
  }

  if (indexStatements.length > 0) {
    lines.push(`-- Indexes`);
    for (const idxStr of indexStatements) {
      lines.push(idxStr);
    }
    lines.push(``);
  }

  if (foreignKeyStatements.length > 0) {
    lines.push(`-- Foreign Key Constraints`);
    for (const fkStr of foreignKeyStatements) {
      lines.push(fkStr);
    }
    lines.push(``);
  }

  return lines.join("\n");
}

export class SqlSchemaGenerator implements SchemaGeneratorPlugin {
  public name = "sql";

  public supports(target: string): boolean {
    const lower = target.toLowerCase();
    return lower.startsWith("sql:") || ["sql"].includes(lower);
  }

  public async generate(ir: SpecIR, outputDir: string, target: string): Promise<void> {
    const sqlContent = generateSqlDdl(ir);
    if (sqlContent) {
      const dbDir = path.join(outputDir, "db");
      fs.mkdirSync(dbDir, { recursive: true });
      fs.writeFileSync(path.join(dbDir, "schema.sql"), sqlContent);
      console.log(pc.green(`   Generated SQL schema DDL at ${path.join(dbDir, "schema.sql")}`));
    }
  }
}
